### ISSUE TITLE
Underscores in the middle of names.

### ISSUE THREAD

**Issue by taylorh140** [hyrious/typst-syntax-highlight#17]
![image](https://github.com/hyrious/typst-syntax-highlight/assets/10996543/d67a14dd-c16e-4f17-a8fe-499817c202f2)
![image](https://github.com/hyrious/typst-syntax-highlight/assets/10996543/7be7796b-86d1-469b-b5ff-2ff0807ddba7)

I believe that the underscores only count as italics when at the beginning or end of a string. So the highlighting gets a bit confused in these cases.

**Comment by hyrious** [comment]
> the underscores only count as italics when at the beginning or end of a string

TIL. Same thing also applies to bolds (`*`).

It seems `\b` is not enough to match the cases. I wonder whether matching the whitespace `(^|\s)` `($|\s)` is correct:

```
foo _bar_buzz_ lorem
foo *bar*buzz* ipsum
```

![image](https://github.com/hyrious/typst-syntax-highlight/assets/8097890/68207110-a1d9-4f2f-bb95-acf5fb6447c1)

**Comment by taylorh140** [comment]
Thanks for the fantastic work. And quick reply. I know that this syntax is
pretty tricky and am glad that you are managing it.
