### ISSUE TITLE
Is it possible to "overlook" typst warnings?

### ISSUE THREAD

**Issue by ondohotola** [hyrious/typst-syntax-highlight#18]
With typst 0.7.0 I am getting this warning (in particular when using tablex)

```
warning: layout did not converge within 5 attempts
```

Which makes the Build return _with Error_

How would done filter these? Or perhaps show them as _with Warnings_?

As I use the _Better Build System_ I have created an issue [there](https://bitbucket.org/iamart/better-build-system/issues/7/see-https-githubcom-hyrious-typst-syntax) as well referring to this one as I don't know which one is _responsible_

**Comment by hyrious** [comment]
It is definitely possible to filter warnings in a build system by writing a [python script](https://www.sublimetext.com/docs/build_systems.html#advanced-example).

However, I'm not in a hurry to bring python into this project. In most of the cases this simple [build system](https://github.com/hyrious/typst-syntax-highlight/blob/main/Typst.sublime-build) just works. You're free to write your own complex build system in your `User` package.

**Comment by istudyatuni** [comment]
Take a look at [LSP for Typst](https://lsp.sublimetext.io/language_servers/#typst)
