### ISSUE TITLE
How to open the resulting PDF after successful compilation?

### ISSUE THREAD

**Issue by ondohotola** [hyrious/typst-syntax-highlight#2]
Is there a way to fire up off an "open $file_base_name.pdf" after successful compilation, or how would one bind that to a key?

**Comment by hyrious** [comment]
Just added a build variant to append `--open` to the typst compile command. You can invoke that with <kbd><kbd>primary</kbd><kbd>shift</kbd><kbd>b</kbd></kbd> then select "Typst - Open".

**Comment by ondohotola** [comment]
Thank you very much. That works VERY well.

I have  no idea how to do a pull request but I suppose the below should qualify for one 

```json
{
  "cmd": ["typst", "compile", "$file"],
  "selector": "source.typst",
  "file_regex": "┌─ (...*?):([0-9]*):?([0-9]*)",
  "env": { "NO_COLOR": "1" },
  "cancel": { "kill": true },
  "variants": 
  [
    {
      "name": "Open",
      "cmd": ["typst", "compile", "$file", "--open"]
    },
    {
      "name": "Make",
      "cmd": ["make"]
    }
  ]
}
```

In other words add a variant to run the `make` command.
