### ISSUE TITLE
Make $ paired

### ISSUE THREAD

**Issue by istudyatuni** [hyrious/typst-syntax-highlight#20]
Like `_` for italic, `*` for bold, `[]`, etc

- When pressing `$` insert `$|$`  (`|` is cursor position)
- When pressing space inside `$$` also double space: `$ | $` (as in typst web app)
- When pressing `$` with some text selected, wrap this text to `$...$`

**Comment by istudyatuni** [comment]
Also I have an issue that `()` not pairing when pressing before `$` or `_`

**Comment by hyrious** [comment]
The `()` auto pairing is not implemented by me but by Sublime Text itself, this is the definition in `Default (platform).sublime-keymap`:

```js
	{ "keys": ["("], "command": "insert_snippet", "args": {"contents": "($0)"}, "context":
		[
			{ "key": "setting.auto_match_enabled", "operator": "equal", "operand": true },
			{ "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true },
			{ "key": "following_text", "operator": "regex_contains", "operand": "^(?:\t| |\\)|]|;|\\}|$)", "match_all": true }
		]
	},
```

As you can see it only pairs when seeing the `(` is followed by `(?:\t| |\\)|]|;|\\}|$)` -- basically spaces and right brackets and line ending.
