### ISSUE TITLE
Spell check mostly disabled.

### ISSUE THREAD

**Issue by taylorh140** [hyrious/typst-syntax-highlight#3]
Spell check seems to be enabled only for the content doesn't need to be checked.

![image](https://github.com/hyrious/typst-syntax-highlight/assets/10996543/da161e84-fda1-4f66-8fcc-bf09b0a2c89c)

F6 to toggle. 

I have been toggling syntax highlighting to check spelling. which is tedious.

**Comment by ondohotola** [comment]
I noted same ( on m2 macbook) and toggling does not make a difference

**Comment by hyrious** [comment]
🤔 That must because of me using `source.typst` instead of `text.typst`.

**Comment by ondohotola** [comment]
Amazing stuff :-)-O
