### ISSUE TITLE
Term should start from newline (except for indentations) and space is required after slash

### ISSUE THREAD

**Issue by istudyatuni** [hyrious/typst-syntax-highlight#39]
![image](https://github.com/hyrious/typst-syntax-highlight/assets/43654815/5c6b2c34-62ae-4642-8777-66828eeaefda)
![image](https://github.com/hyrious/typst-syntax-highlight/assets/43654815/355fa69e-9de5-4485-869a-6f440c6c8b59)

```typ
asdf / asdf:
/asdf:
```

**Comment by hyrious** [comment]
Fixed in 29b55fd57e0e631962a160b43e07450937a0ac46.

**Comment by hyrious** [comment]
There's a special case:

```typst
#{ [/ term: definition] }
```

Currently I only matches `/ ` at the beginning of the line (or with some leading spaces). So code above won't be highlighted well. But I guess nobody writes terms like that?

**Comment by istudyatuni** [comment]
I write something like this, although it's rare, and I think it looks pretty good already. Example:

<details><summary>Image</summary>
<p>

![image](https://github.com/hyrious/typst-syntax-highlight/assets/43654815/adc6ac2e-362e-4a91-9d5d-b8fea77d435f)

</p>
</details> 

```typ
#usage[
  #samples("ない|ません", title: false)[
    #let base = ("食べ", "見", "寝")
    #casual-polite-list((
      for b in base {
        let b = [#b;#grs[る]]
        ([/ #b + ない:],
         [/ #b + ません:
          / #b + ないです:
        ])
      }
    ))
  ]
]
```
