### ISSUE TITLE
Include more examples in the syntax test file

### ISSUE THREAD

**Issue by Alexey-T** [hyrious/typst-syntax-highlight#4]
- the `_` and `*` are the only possible italic+bold symbols? and `_*` is only possible italic-and-bold? if other combinations are possible it would be good to include them to test file.

- `$` math blocks are ok. Markdown supports also `$$` marks for multi-line math blocks. no such symbols here?

**Comment by Alexey-T** [comment]
If underline  and crossed-text are possible, it is good to include samples too.

**Comment by hyrious** [comment]
> the _ and * are the only possible italic+bold symbols?

**Comment by Alexey-T** [comment]
if `_*a*_` is bold+italic, then `*_a_*` must work too?

and what about `_*a_*`?

**Comment by hyrious** [comment]
> if `_*a*_` is bold+italic, then `*_a_*` must work too?

Yes.

> and what about `_*a_*`?

This is a syntax error in Typst. You can try it on its online app: https://typst.app.

Detecting such errors is not part of the duty of this sublime plugin, which is already covered by the compiler.
