### ISSUE TITLE
Single line Raw Text segment ruins state

### ISSUE THREAD

**Issue by taylorh140** [hyrious/typst-syntax-highlight#8]
the code here:
```typst
This text is properly syntaxed <<<

#h(1cm) ``` Purple_Rain.mp3```

Evil purple now occurs <<<
```
causes:
![image](https://github.com/hyrious/typst-syntax-highlight/assets/10996543/2de0eb35-672d-4194-b404-2d857951bda8)

**Comment by taylorh140** [comment]
I notice if i add a space after the last ``` it fixes the syntax. perhaps that helps.

**Comment by hyrious** [comment]
Yep, just noticed Typst supports code blocks that are written inline. That's why the rules from markdown doesn't work.
